version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing packages ...$(date)"
      - yum install -y unzip wget jq
      - curl -LO https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform_1.7.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - /usr/local/bin/terraform -version
      - pip install ansible
      - yum update -y

  build:
    commands:
      - echo "Terraform apply started at" $(date)
      - terraform init
      - terraform apply -auto-approve | tee terraform_apply.log
  post_build:
    commands:
      - echo "Terraform apply completed at" $(date)
