version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing packages ... $(date)"
      - yum install -y unzip wget jq
      - curl -LO https://releases.hashicorp.com/terraform/1.8.4/terraform_1.8.4_linux_amd64.zip
      - unzip terraform_1.8.4_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - /usr/local/bin/terraform -version
      - pip install ansible
      - yum update -y

  pre_build:
    commands:
      - echo "Initializing Terraform with remote backend.tf which has current state in S3 bucket"
      - terraform init
      - echo "Import existing AWS resources to avoid duplication resource creation error in codebuild container by lambda"
      - chmod +x import-terraform-resource-state.sh
#      - ./import-terraform-resource-state.sh
#      - terraform plan

  build:
    commands:
      - echo "Terraform apply started with Ansible provisioning triggers at time $(date)"
      - terraform apply -auto-approve
      - aws ec2 describe-instances --filters "Name=tag:Name,Values=rhel96-ec2" --query "Reservations[].Instances[].State.Name"

  post_build:
    commands:
      - echo "Terraform apply completed at $(date)"
